---
- name: Fail if ip is not Valid
  fail:
    msg: "Check {{ build_ip }}! It failed a general IP validation test"
  when: not build_ip | validate_ip

- name: Search for IP address in Satellite
  uri:
    url: "https://{{ satellite_fqdn }}/api/v2/hosts?search=ip={{ build_ip }}"
    method: GET
    user: "{{ satellite_user }}"
    password: "{{ satellite_password }}"
    force_basic_auth: 1
    validate_certs: no
    return_content: yes
  register: satellite_search

- name: Fail when IP address is claimed
  fail:
    msg: "{{ satellite_search.json.results[0].name }} has claimed that IP address"
  when: satellite_search.json.results | length > 0